- package-lock.json
- src/RpcClient.ts
- src/types/das-types.ts
Fixed: 
- getAsset response types. 
This will now work on ex:) 
const files = x.rpc.getAsset('veSBHYnvUpUvpULPh1FLCmCbCtfVxG2uWncSi6QWnSu').then(x => console.log(x.interface))
Tested: 
- Local
> fixing getAssets

- README.md
- package-lock.json
- package.json
- src/Helius.ts
- src/types/enums.ts
- src/types/types.ts
- src/utils/mintApi.ts
- Delegate/Revoke collection authority to/from any address provided (defaults to Helius Mint API authority if none is provided).
> feat: delegate/revoke collection authority

- package-lock.json
- src/Helius.ts
- Corrected the logic in the if statement to correctly validate paths starting with /v0 or /v1
- Updated the NPM packages to reflect the correct version number in package-lock.json
> Fix for issue #55

- package-lock.json
- package.json
- feat: ✨ Add removeAddressesFromWebhook method #66
> Update version number 1.2.5

- src/types/das-types.ts
This PR aims to fix the import for `FullRwaAccount` after it was changed from `FullAccount`
> [Fix] Import for `FullRwaAccount`

- src/RpcClient.ts
- src/types/das-types.ts
This PR aims to add the [getTokenAccounts method](https://docs.helius.dev/compression-and-das-api/digital-asset-standard-das-api/get-token-accounts) to the SDK
> [Feat] Add `getTokenAccounts` Method

- src/RpcClient.ts
- src/types/das-types.ts
This PR aims to add the [`getNftEditions` method](https://docs.helius.dev/compression-and-das-api/digital-asset-standard-das-api/get-nft-editions) to the SDK
> [Feat] Add `getNftEditions` Method

- package-lock.json
- package.json
- fix: 👷 `CompressedNftEvent` field in `TransactionEvent` is now an array #69 
- fix: 👷 Add `metadata` field to `CompressedNftEvent` #70 
- fix: 👷 Import for `FullRwaAccount` #72 
- fix: 👷 Change `delegate` field in `SearchAssetsRequest` to `string` #73 
- fix: 👷 Add `TransactionType` enum to `Webhook` interface #78 
- fix: 👷 Update documentation #79
- feat: ✨ Add `getRwaAsset` #71
- feat: ✨ Add `getPriorityFeeEstimate` method #74 
- feat: ✨ Add `getTokenAccounts` method #75 
- feat: ✨ Add `getNftEditions` method #77 
- feat: ✨ Add Jest testing framework #80
> 1.3.0 Update

- package-lock.json
- package.json
- fix: 👷 Update `grand_total` Type #82
- fix: 👷 `PriorityLevel` Enum #84 
- feat: ✨ Add `sendSmartTransaction` #83
> 1.3.1 Update

- src/RpcClient.ts
This PR aims to update the `sendSmartTransaction` functionality based on the new and improved functionality introduced in the Rust SDK after the inital commits made here
> feat(txts): Update `sendSmartTransaction` Functionality

- README.md
- src/RpcClient.ts
This PR aims to streamline the functionality of `sendSmartTransaction`. It also abstracts out the creation functionality and provides it as a new function `createSmartTransaction`
> feat(txts): Update `sendSmartTransaction` and Add `createSmartTransaction`

- .eslintrc.json
- src/types/das-types.ts
This PR aims to address missing response types, specifically a token's standard and mint extensions
> fix(das-types): Missing Response Types

- src/RpcClient.ts
This PR aims to correctly pass in the `feePayer` to the smart transaction creation process, if provided
> feat(txts): Add Fee Payer to Smart Transaction Creation

- src/types/enums.ts
- Add `MplCoreAsset` to interface enum
> Add `MplCoreAsset` to interface enum

- README.md
This PR aims to update the documentation to add a section on Jito smart transactions and the relevant helper methods. It also adds a section on smart transactions
> feat(docs): Add Jito Smart Transactions

- package-lock.json
- package.json
- fix: 👷 Better Error Logging for `getComputeUnits` #98 
- fix: 👷 Missing Response Types #99 
- fix: 👷 Address Issue When Using Different Fee Payer Account #100 
- fix: 👷 `sendSmartTransaction` Times Out But Transaction Is Confirmed #103 
- fix: 👷 Bump axios from 0.27.2 to 1.7.2 #107
- feat: ✨ Implement Jito Smart Transactions #101  
- feat: ✨ Add Fee Payer to Smart Transaction Creation #104
- feat: ✨ Standardize Code Styling #105 
- feat: ✨ Add `MplCoreAsset` to Interface Enum #106
- feat: ✨ Add Jito Smart Transactions (to Docs) #108
> 1.3.4 Update

- src/types/das-types.ts
Changed capitalization otherwise it does not work
> Changed capitalization for TokenType

- package-lock.json
- package.json
This PR aims to import `bs58` explicitly as a dependency. This should help fix #120
> fix(deps): Add `bs58`

- package-lock.json
- package.json
- fix: 👷 Change capitalization for TokenType #113  
- fix: 👷 Better Formatting #115 
- fix: 👷 pollTransactionConfirmation not recognizing finalized transactions #118 
- fix: 👷 Add `bs58` #122 
- fix: 👷 Update `DisplayOptions` and `GetAssetDisplayOptions` #123 
- fix: 👷 Add `token_extensions` for `TokenAccount` #124 
- fix: 👷 Better `getComputeUnits` #125 
- fix: 👷 Better `pollTransactionConfirmation` #126 
- fix: 👷 Update README.md #127 
- feat: ✨ refactor smart transaction sender & confirmation #114   
- feat: ✨ Add `serializeOptions` For Legacy Transactions #117
> 1.3.5 Update

- package-lock.json
- package.json
- fix: 👷 Update `sendSmartTransaction`'s `lastValidBlockHeightOffset` type definition #132 
- fix: 👷 Update tx encoding casing #135 
- fix: 👷 Add total_price to PriceInfo #136 
- fix: 👷 Add `showNativeBalance` to `DisplayOptions` #137 
- fix: 👷 Improve getPriorityFeeEstimate Error Handling #138 
- fix: 👷 Bump axios and @irys/sdk #139 
- fix: 👷 Change `none` to `min` #141 
- fix: 👷 Explicitly Define `lastValidBlockHeightOffset` for `sendSmartTransaction` #142
> 1.3.6 Update

- README.md
- package.json
- src/RpcClient.ts
- src/constants.ts
- src/index.ts
- src/types/types.ts
Adds a version of `sendTransaction` call that supports the `validatorAcls` parameter
> Add send transaction to sdk

- src/types/das-types.ts
fixes #149
Add nativeBalanceInfo type
Add nativeBalance property of type nativeBalanceInfo to GetAssetResponseList type
> Add missing field nativeBalance for getAssetsByOwner response

- src/RpcClient.ts
- src/constants.ts
- src/types/das-types.ts
- src/types/types.ts
This PR aims to improve the sending and polling logic for `sendSmartTransaction` by improving `pollTransactionConfirmation` and re-implementing it into `sendSmartTransaction` to replace the previous, outdated custom polling logic
> feat(optimized_transaction): Improve Sending and Polling Logic

- package-lock.json
- package.json
- fix: 👷 Add missing field nativeBalance for getAssetsByOwner response #162 
- fix: 👷 Bump secp256k1 from 5.0.0 to 5.0.1 #164  
- feat: ✨ feat(optimized_transaction): Improve Sending and Polling Logic #163
> 1.4.2 Update

- README.md
- src/RpcClient.ts
- src/types/types.ts
Also separated SmartTransactionOptions into SendSmartTransactionOptions and CreateSmartTransactionOptions. Both functions don't actually use all of the parameters, so its confusing devex
> fix: add clear documentation for sendTransaction

- src/RpcClient.ts
- Update Jupiter API endpoints
> fix: Update Jupiter swap API endpoints to latest version

- src/utils/get-helius-endpoints.ts
This PR aims to update the API URLs in the SDK to resolve #157
> fix(endpoints): Update API URLs

- package.json
- pnpm-lock.yaml
- src/RpcClient.ts
This PR aims to add wallet adapter support to smart transactions by adding the `createSmartTransactionWithWalletAdapter` and `sendSmartTransactionWithWalletAdapter` functions
> feat(optimized_transaction): Add Wallet Adapter Support

- .cursor/rules
This PR aims to add rules for Cursor to help aid in development (i.e., we're adding instructions/system prompts for LLMs) 🤖
> feat(ai): Add Cursor Rules

- README.md
- src/RpcClient.ts
- src/types/types.ts
This PR enhances the `executeJupiterSwap` method to utilize the latest Jupiter API endpoints and include transaction landing optimizations, significantly improving swap reliability during network congestion.
- **Updated Jupiter API Integration**: Switched to the latest Jupiter quote and swap API endpoints for better performance and price discovery
- **Transaction Landing Optimizations**:
- Added priority fee management with configurable levels (`low`, `medium`, `high`, `veryHigh`, `unsafeMax`)
- Added support for transaction retries during congestion
- Improved slippage handling with fixed slippage bps instead of dynamic slippage
- Added ability to restrict intermediate tokens for better routing
- **Enhanced Return Data**:
- Added transaction confirmation status tracking
- Included …
> Enhance the `executeJupiterSwap` method

- README.md
- examples/EXAMPLES_OVERVIEW.md
- src/RpcClient.ts
This PR aims to enhance the current staking functionality to add the following methods complete with documentation:
- `createWithdrawTransaction()`
- `getStakeInstructions()`
- `getUnstakeInstruction()`
- `getWithdrawInstruction()`
- `getWithdrawableAmount()`
> feat(staking): Add More Staking Methods

- package.json
- fix: 👷 #166  
- fix: 👷 #167 
- fix: 👷 #169 
- fix: 👷 #170 
- fix: 👷 #178 
- fix: 👷 #179 
- fix: 👷 #180 
- fix: 👷 #181 
- fix: 👷 #184 
- feat: ✨ #171 
- feat: ✨ #172 
- feat: ✨ #174 
- feat: ✨ #183 
- feat: ✨ #185 
- feat: ✨ #186
> 1.5.0 Update

- CONTRIBUTING.md
- LICENSE
- README.md
This is a draft Contributing.md to set a guideline for contributors, both new and experienced developers.
@0xIchigo your review would be greatly appreciated.
> docs: add contribution guide to improve developer experience

- CONTRIBUTING.md
This PR aims to make minor updates to `CONTRIBUTIONS.md` to keep it in line with the contributions guide we have for the Rust SDK
> fix(docs): Minor Contribution Doc Edits

- src/Helius.ts
This PR aims to update the `_editWebhook` internal method so we always pass in the complete payload to resolve #197
> fix(webhook): Update `_editWebhook`
