helius-labs/helius-sdk

README.md, package-lock.json, package.json, src/Helius.ts
Documentation suggests that we should do the following in order to listen to NFT sales on ME:
```ts
await this.helius.createWebhook({
accountAddresses: [Types.Source.MAGIC_EDEN],
transactionTypes: [Types.TransactionType.NFT_SALE],
webhookURL: 'https://my-ngrok.io/webhooks',
webhookType: WebhookType.ENHANCED,
});
```
--------
Whereas in reality we should use:
```ts
await this.helius.createWebhook({
accountAddresses: [Types.Address.MAGIC_EDEN_V2],
transactionTypes: [Types.TransactionType.NFT_SALE],
webhookURL: 'https://my-ngrok.io/webhooks',
webhookType: WebhookType.ENHANCED,
});
```
`accountAddresses` takes an array of strings (account addresses) which is not type safe as it can accept ANY (faulty) string like `"MAGIC_EDEN"` string from `Types.Source.MAGIC_EDEN` when in reality it expects …
=> Webhook params validation

package-lock.json, src/Helius.ts, src/types/types.ts
All operations using the edit api are failing because we pass in the wallet and webhookID into the body.
This pr removes those fields from the object, and also makes all edit request params optional, since the remaining fields are populated from the original webhook config.
The diff is unusually large due to prettier formatting.
=> Edit api fix

README.md, package-lock.json, package.json, src/Helius.ts, src/RpcClient.ts, src/index.ts, src/utils/cluster.ts, src/utils/index.ts
This PR adds new readonly properties to the `Helius` class, a utility function and a new `RpcClient` class as a tooling for awesome RPC calls.
---
**Following fields were added to the `Helius` class**
```ts
public readonly cluster: Cluster;
public readonly endpoint: string;
public readonly rpc: RpcClient;
```
and existing `rpcClient` was renamed to a more appropriate name `connection`
```ts
public readonly connection: Connection;
```
---
**Following utility functions were added**
`heliusClusterApiUrl` - it's inspired by `clusterApiUrl` function from the `solana-web3.js` package
---
**Following was achieved with the `RpcClient` class**
`RpcClient` exposes 3 functions: `airdrop`, `getLatestBlockhash`, `getCurrentTPS` (migrated from the `Helius` class)
This way, SDK consumers can call …
=> chore: add new readonly Helius properties

package-lock.json, package.json, src/Helius.ts
`createCollectionWebhook` is not working when fetching collections via collection NFTs since the query parameter is wrongly set to use `firstVerifiedCreators` on lines 284-286, in the while loop.
In order to replicate this error you would need to fetch a collection with more than 10000 items via collection NFT. e.g. y00ts collection on: `4mKSoDDqApmF1DqXvVTSL6tu2zixrSSNjqMxUnwvVzy2` because the issue is in the while loop which is triggered if there is pagination token present.
=> fix: createCollectionWebhook query params

src/Helius.ts
PDA addresses are not on curve so these `PublicKey.isOnCurve(...)` validations prevent any PDA inputs like AuctionHouse contract address etc.
Resolves: https://github.com/helius-labs/helius-sdk/issues/19
=> fix: deprecate isOnCurve validation

src/types/types.ts
This PR fixes nft event type
response returned :
```
nft: {
amount: 1000000000,
buyer: '',
description: '3dkovHUm4UJRGjtRmapGJzHjwQFPjaGiPoFjNQxPj1sS listed Rise of the Gorecats #5 for 1 SOL on METAPLEX.',
fee: 5000,
feePayer: '3dkovHUm4UJRGjtRmapGJzHjwQFPjaGiPoFjNQxPj1sS',
nfts: [Array],
saleType: 'UNKNOWN',
seller: '3dkovHUm4UJRGjtRmapGJzHjwQFPjaGiPoFjNQxPj1sS',
signature: '5nQaKLntqsXKLBqpAZmB6JGjpMWPszbEzUT4PuE4fTPyhyFc87sKvwDtYdiMJnujVym8oc4KUaCCtPhbhhSWAtJr',
slot: 203451432,
source: 'METAPLEX',
staker: '',
timestamp: 1679379071,
type: 'NFT_LISTING'
}
```
=> fix: nft event type

.gitignore, package-lock.json, src/Helius.ts, src/types/types.ts, tests/test.ts
We need to explicitly specify the fields when we call "putWebhook" to avoid causing breaking changes when we add new fields to the webhook response.
Tested against my personal Helius account.
=> fix: specify fields on webhook update

src/types/types.ts
Compressed nft event is an array
See https://xray.helius.xyz/tx/5VCfxHnEmDMtzgr8qJJeUg3nSSQvhdh27qSEoWZsWBCC9KrEPaS3gZrM6Ar42JyT9hTMSpbW89d9XvBmjN4PMmvt?network=devnet
closes #68
=> Compressed nft event should be an array

src/types/types.ts
`metadata` field missing in ``CompressedNftEvent``
=> fix: add metadata type for CompressedNftEvent

src/types/das-types.ts
This PR aims to add the `tokenType` parameter to `SearchAssetsRequest`. We allow users to filter by a token type via the Fungible Token Extension for search asset calls, however, this isn't currently possible with the SDK
=> Add tokenType Param to SearchAssetsRequest

src/types/das-types.ts
This PR addresses #63 by changing the `SearchAssetsRequest`'s `delegate` type to `string` since it expects an address
=> [Fix] Change `delegate` type to `string`

src/types/types.ts
This PR seeks to address #15 by adding the `TransactionType` enum to the `Webhook` interface for better type support
=> [Fix] Add `TransactionType` Enum to `Webhook` Interface

src/RpcClient.ts, src/types/enums.ts, src/types/types.ts
This PR aims to add the [`getPriorityFeeEstimate` method](https://docs.helius.dev/solana-rpc-nodes/alpha-priority-fee-api#helius-priority-fee-api-an-improved-solution) to the SDK
=> [Feat] Add `getPriorityFeeEstimate` Method

src/types/das-types.ts
This PR directly addresses #64 by updating `GetAssetResponseList`'s `grand_total` field to a `number` or `undefined`
=> [Fix] Update `grand_total` Type

src/types/enums.ts
This PR aims to address the `PriorityLevel` enum, so everything is named correctly
=> [Fix] `PriorityLevel` Enum

src/RpcClient.ts
This PR aims to address the issue outlined in #95 by stringifying the error object
=> fix(txts): Better Error Logging For `getComputeUnits`

src/RpcClient.ts
Fixes #102 by throwing timeout error only if the current block height is greater than the `lastValidBlockHeight` returned by `getLatestBlockhash` used when creating the transaction.
=> fix(txts): `sendSmartTransaction` Times Out But Transaction Is Confirmed

.eslintrc.json, .prettierrc, src/types/enums.ts
This PR aims to temporarily disable the strict ESLint errors causing build issues and fix the formatting for the `.prettierrc` and `src/types/enums.ts` files
=> fix(prettier): Better Formatting

src/RpcClient.ts
Between the 5 seconds retry interval a transaction can enter into the finalized phase without getting checked while it was confirmed. This could result as a transaction not getting recognized as confirmed yet it is.
=> Fix pollTransactionConfirmation not recognizing finalized transactions

src/RpcClient.ts
This PR aims to modify the serialization process in `createSmartTransactions`. This is done so users can specify whether they would like to require all signatures or signature verification, giving them greater control over the smart transaction creation process
=> feat(txts): Add `serializeOptions` For Legacy Transactions

src/types/das-types.ts
This PR aims to add the necessary display options to `DisplayOptions` and `GetAssetDisplayOptions` to close #62. The types added are in line with [the Rust SDK's current types](https://github.com/helius-labs/helius-rust-sdk/blob/cbd01242807cd4aaff3dc27d21d98163a7999e8a/src/types/options.rs#L3-L28)
=> fix(types): Update `DisplayOptions` and `GetAssetDisplayOptions`

src/RpcClient.ts, src/types/das-types.ts
This PR aims to add the `token_extensions` field to `TokenAccount` to resolve #121. This PR also removes the unused imports in `RpcClient.ts`
=> fix(types): Add `token_extensions` for `TokenAccount`

README.md, src/RpcClient.ts
This PR aims to align with the [Rust SDK's recent PR](https://github.com/helius-labs/helius-rust-sdk/pull/60), which allows the user to skip signature verification for `getComputeUnits` if no signers are provided
=> fix(txts): Better `getComputeUnits`

src/RpcClient.ts
`lastValidBlockHeightOffset` is meant to default to `150`, and should not be required by the consumer to specify. So I'm simply updating the type here to be an optional parameter because if we don't the change would be seemingly non-backwards-compatible (users **can** just specify `lastValidBlockHeightOffset` of `150` on v1.3.5 though) and might require a major version change otherwise since this could be considered a "breaking" change, if typescript fails to pass the type-checker
This resolves https://github.com/helius-labs/helius-sdk/issues/131
=> Update `sendSmartTransaction`'s `lastValidBlockHeightOffset` type definition

src/types/enums.ts
Priority Fee API expected encoding in lowercase but the enum values are in uppercase so the payload was always incorrect
=> Update tx encoding casing

src/types/das-types.ts
This PR aims to add the `total_price` field to the `PriceInfo` interface, which resolves #130
=> fix(types): Add `total_price` to `PriceInfo`

src/types/das-types.ts
This PR aims to resolve #129 by adding the `showNativeBalance` field to `DisplayOptions`
=> fix(types): Add `showNativeBalance` to `DisplayOptions`

src/RpcClient.ts
This PR aims to resolve #133, where the SDK will fail silently and return `undefined`, by improving `getPriorityFeeEstimate`'s error handling
=> fix(api): Improve `getPriorityFeeEstimate` Error Handling

src/RpcClient.ts
This PR aims to explicitly define `lastValidBlockHeightOffset` for `sendSmartTransaction` all because TypeScript will have a conniption if it isn't. We default `lastValidBlockHeightOffset` to 150 in the function params, but this PR goes a step further to explicitly define it via nullish coalescing to make the compiler happy
=> fix(txts): Explicitly Define `lastValidBlockHeightOffset` for `sendSmartTransaction`

src/types/types.ts
This PR aims to change the `none` priority fee level to `min`, thereby resolving #140
=> fix(types): Change `none` to `min`

src/types/enums.ts
Account webhooks have no existed for a while, removing it from the sdk types to avoid confusion
=> Removing account webhook type

src/RpcClient.ts
This PR aims to fix the bug where we add the `blockhash.lastValidBlockHeight` and `lastValidBlockHeightOffset` by using a new variable `lastValidBlockHeight` that calculates the minimum between the two
=> fix(txs): Last Valid Block Height Issue

src/RpcClient.ts, src/types/types.ts
This PR aims to add a priority fee cap for smart transactions. The idea is that the user should be able to cap priority fees at a specific number and use that instead of what is strictly returned by the Priority Fee API. This PR also reworks the send options for smart transactions to make it more intuitive
=> feat(txs): Add a Priority Fee Cap

src/Helius.ts, src/types/types.ts
Hi all!
Had a need for experimenting with the parse transactions endpoint and noticed it wasn't implemented in the sdk.
Somebody also explicitly asked for it, so created this PR.
Closes #28
=> Add method for parse transactions endpoint

README.md, src/RpcClient.ts, src/types/types.ts
Added support for executing token swaps through Jupiter Exchange with automatic priority fee estimation and compute unit calculation.
- Added `executeJupiterSwap()` method with dynamic slippage protection
- Added types `JupiterSwapParams` and `JupiterSwapResult` 
- Added documentation and examples
```typescript
const result = await helius.rpc.executeJupiterSwap({
inputMint: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v', // USDC
outputMint: 'So11111111111111111111111111111111111111112', // SOL
amount: 500000, // 0.5 USDC
maxDynamicSlippageBps: 200, // 2% maximum dynamic slippage
}, wallet);
```
No breaking changes. Tested with various token pairs and configurations.
=> Add Swap Helper

src/Helius.ts
This PR aims to address the fact that webhooks use `https://api.helius.xyz/` for both mainnet and devnet. This is separate from our other APIs which use `https://api.helius.xyz/` for mainnet and `https://api-devnet.helius.xyz/` for devnet. Here, we introduce a helper function for minimal disruption as we'll be rewriting the entire SDK soon
=> fix(webhook): Update API URL

src/RpcClient.ts, src/types/types.ts
This PR aims to add the `broadcastTransaction` method, which broadcasts a fully signed transaction (object or serialized) and polls for its confirmation
=> feat(txs): Add `broadcastTransaction`

src/RpcClient.ts
This PR aims to remove duplicate code by refactoring the `sendSmartTransaction()` and `sendSmartTransactionWithWalletAdapter()` methods with `broadcastTransaction()`. We also default `skipPreflight` to `false` in `broadcastTransaction()` to mimic the old behavior for the smart transaction sending functionality
=> feat(txs): Refactor Send Smart Transaction Logic with `broadcastTransaction`

src/Helius.ts, src/types/types.ts
This PR aims to remove calls to the deprecated mintlist API and all relevant types. Instead, developers should use use the [DAS API](https://www.helius.dev/docs/api-reference/das)
=> feat(mintlist): Remove Deprecated Mintlist Calls and Relevant Types

README.md, docs/_config.yml, examples/zk/getMultipleNewAddressProofsV2.ts, tsconfig.json
This PR aims to make GitHub happy by putting the `docs` dir back in and redirecting it to the README
=> fix(docs): Make GitHub Happy With Docs Dir

src/rpc/heliusRpcApi.ts, src/rpc/index.ts
This PR aims to help resolve #214 by making the `ResolvedHeliusRpcApi` type more explicit to resolve `HeliusClient = any` intellisense issues
=> fix(types): Make `ResolvedHeliusRpcApi` Type Explicit
